### PR TITLE
Mraa and upm fixes

### PR DESCRIPTION
**Pull request by whbruce**
mraa: Added ft4222 PACKAGECONFIG entry and cleaned up cmake tools install
upm: Remove nodejs and swig-native from DEPENDS, will be handled by PACKAGECONFIG (see issue #6)

### CODE REVIEW

**Comment by tripzero** [comment]
test it please

**Comment by tripzero** [comment]
ok to test

**Comment by tripzero** [comment]
@kad looks like the CI genie doesn't obey me.  Do I have to be "admin" status?

**Comment by kad** [comment]
ok to test

global admins currently me, @mythi @pohly 
I need to find way to enable it more fine-grained :(

**Pull request merged**
