### PR TITLE
mraa: Update to 1.1.1

### PR DESCRIPTION
**Pull request by arfoll**
Adds wifi module LED support on GT

### CODE REVIEW

**Comment by tripzero** [comment]
@arfoll /var/lib/jenkins/ostro-worker-15-slot-1-Wv1AW/ostro-os/build/tmp-glibc/work/edison-ostro-linux/upm/0.7.0-r0/git/src/l3gd20/l3gd20.cxx:59:59: error: 'mraa_iio_get_mounting_matrix' was not declared in this scope

Can you look into this?  https://ostroproject.org/jenkins/job/build_intel-corei7-64/2037/console

**Comment by arfoll** [comment]
:( this depends on a UPM update for the IIO api. @pylbert can we get the UPM new release asap?

**Comment by tripzero** [comment]
When the upm finishes building by CI, we'll merge and this should start working.

**Comment by pylbert** [comment]
@arfoll  and @tripzero, I updated upm for iio and tagged a 0.7.2 version with the required changes to build against mraa 1.1.1.  Let me know how you would like to handle merging this.  One way would be for @arfoll to add a rename of the upm recipe to this PR (fixed in upm_0.7.2.bb).

**Comment by tripzero** [comment]
retest please

**Comment by tripzero** [comment]
ok to test

**Comment by tripzero** [comment]
@kad CI doesn't seem to like my magic words.  We need to test this again now that upm has been merged.

**Comment by kad** [comment]
phrase "ok to test" is only used for PRs from people who are not part of this organization.
pharse for retest is "test it please". "it" was missing in your comment.

**Pull request merged**
