### PR TITLE
mraa: Update to v1.3.0

### PR DESCRIPTION
**Pull request by arfoll**
This negates the need for the 2 previous patches included

Signed-off-by: Brendan Le Foll brendan.le.foll@intel.com

### CODE REVIEW

**Comment by tripzero** [comment]
ERROR: mraa-1.3.0-r0 do_package_qa: QA Issue: mraa rdepends on json-c, but it isn't a build dependency, missing json-c in DEPENDS or PACKAGECONFIG? [build-deps]
05:21:29 ERROR: mraa-1.3.0-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.

Probably needs DEPENDS+=json-c

Not sure why this is only showing up now...

**Comment by arfoll** [comment]
Indeed, thanks, not forcing it either way could cause v.awkward issues if it's in the sysroot as your build indicated. I can rebase the two together if you think that's better.

**Comment by tripzero** [comment]
> I can rebase the two together if you think that's better.

yes, please.

**Comment by arfoll** [comment]
Thanks!

**Pull request merged**
